---
- name: create file
  hosts: all
  tasks:
        - name: creating an empty file
          file:
                path: /home/bst83356/demo-file.txt
                state: touch
          become: yes
