---
- name: create user
  hosts: all
  vars: 
    host_key_checking: false
  tasks:
        - name: create a user named rio
          user:
                name: rio
                uid: 5067
                state: present
