---
- name: checking connection with windows vm
  hosts: win
  become: false
  tasks:
        - name: ping windows vm
          ansible.windows.win_powershell:
            script: |
              Test-Connection -ComputerName 10.10.35.126
         
