---
- name: ansible
  hosts: all
  vars: 
       greetings: "{{ greetings }}"
       username: "{{ username }}"
  tasks:
    - name: Ansible greetings
      debug:
        msg: "{{ greetings }} {{ username }}, Let's learn ansible variables"
