---
- name: ansible
  hosts: all
  semaphore_vars: 
    greetings: "{{ greetings }}"
  tasks:
    - name: Ansible variable usage
      debug:
        msg: "{{ greetings }}, Let's learn ansible variables"
