---
- name: ansible
  hosts: all
  vars: 
      greetings: "{{ greetings }}"
      username: "{{ username }}"
  tasks:
    - name: Ansible variable usage
      debug:
        msg: "{{ greetings }} {{ username }}, Let's learn ansible variables"
